// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteTecnicoBenner.Infrastructure.Data;

#nullable disable

namespace TesteTecnicoBenner.Migrations
{
    [DbContext(typeof(EstacionamentoContext))]
    [Migration("20250911143409_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TesteTecnicoBenner.Models.Preco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorHoraAdicional")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHoraInicial")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VigenciaFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VigenciaInicio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Precos");
                });

            modelBuilder.Entity("TesteTecnicoBenner.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Saida")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorCobrado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
